
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
format = '$symbol '
success_symbol = '[❯](bold green)'
error_symbol = '[NOPE!](bold red)'

[shlvl]
format = '[$symbol$shlvl]($style) '
repeat = true
symbol = '❯'
repeat_offset = 1
disabled = false

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
read_only = '[] '
read_only_style = 'bold red'
truncation_symbol = '…/' # custom
# usually the truncation is at the third dir unless a git repo
# is found, in which case it stops at the repo root dir (defaults
# to `true`). Worktrees are seen as git repos themselves. Setting
# this to `false` prevents truncating at the worktree dir, revealing
# the root repo dir name and making things clearer.
#
# examples:
#   - true -> .../main
#   - false -> .../<repo>/worktrees/main
truncate_to_repo = false

[git_commit]
format = '[\($hash$tag\)]($style) '
style = 'purple' # custom
tag_disabled = false
tag_symbol = ' • ' # custom
