# core
tap "homebrew/bundle"
brew "mas"
brew "ansible"
brew "stow"
brew "git"
brew "git-lfs"

# fonts
tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"

# shell/terminal
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"
cask "iterm2"

# utils
brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "jq"
brew "mkcert"
brew "nss"
brew "ripgrep"
brew "xh"
brew "zoxide"

# dev
tap "oven-sh/bun"
brew "gh"
brew "glab"
brew "go"
brew "fnm"
brew "oven-sh/bun/bun"
cask "docker"

# UI apps
cask "authy"
cask "google-chrome"
cask "notion"
cask "telegram"
cask "slack"
cask "discord"
cask "zoom"
cask "steam"

# NeoVim
brew "neovim"

# VS Code
cask "visual-studio-code"
vscode "a-h.templ"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc-pack"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "jdinhlife.gruvbox"
vscode "jock.svg"
vscode "kamikillerto.vscode-colorize"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode.makefile-tools"
vscode "redhat.vscode-yaml"
vscode "unifiedjs.vscode-mdx"
vscode "vercel.turbo-vsc"
vscode "vscodevim.vim"